package com.scp.markdown

import com.scp.model.ContextEntry
import com.scp.model.ContextType
import com.scp.model.port.MarkdownStore
import com.scp.model.port.SessionMarkdown
import kotlinx.datetime.Instant
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.locks.ReentrantLock
import kotlin.concurrent.withLock

/**
 * Human-readable mirror, laid out project-first then date-first:
 *
 * ```
 * storage/projects/{project}/
 *   PROJECT.md                                  index — sessions newest first
 *   LATEST.md                                   copy of the newest session (the resume anchor)
 *   2026-08-05T14-25-30Z-claude-code-a3f9c1d2.md
 * ```
 *
 * Session filenames are UTC and colon-free (Windows forbids `:` in filenames), so they sort
 * lexicographically in chronological order and a directory listing alone answers "who worked
 * on this, when". Content arrives already redacted. Every write is atomic (temp file + move)
 * so a crash never leaves a half-written mirror.
 */
public class FileMarkdownStore(private val markdownRoot: Path) : MarkdownStore {
    override fun write(sessionMarkdown: SessionMarkdown): String {
        val session = sessionMarkdown.session
        val dir = markdownRoot.resolve(sanitizeForDirectory(sessionMarkdown.project.name))
        Files.createDirectories(dir)
        val target = dir.resolve(sessionFileName(session.startTime, session.toolName, session.id))

        // The three writes below must land as a set. UpdateContextUseCase deliberately releases
        // the database write lock before mirroring, so two agents updating one project otherwise
        // interleave and leave PROJECT.md's "Resume here" block naming one session while
        // LATEST.md — the file that block links to as "Full detail" — holds another's body.
        // Per-directory so unrelated projects never wait on each other.
        lockFor(dir).withLock {
            val body = render(sessionMarkdown)
            writeAtomically(dir, target, body)
            // LATEST.md is a plain copy, not a symlink: symlink creation on Windows needs elevation
            // or developer mode, and a mirror that silently fails to update is worse than a copy.
            writeAtomically(dir, dir.resolve(LATEST_FILE), body)
            writeAtomically(dir, dir.resolve(INDEX_FILE), renderIndex(dir, sessionMarkdown))
        }
        return target.toAbsolutePath().toString()
    }

    private fun writeAtomically(dir: Path, target: Path, content: String) {
        val temp = Files.createTempFile(dir, ".scp-", ".md.tmp")
        try {
            Files.writeString(temp, content)
            try {
                Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
            } catch (_: java.nio.file.AtomicMoveNotSupportedException) {
                Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING)
            }
        } finally {
            Files.deleteIfExists(temp)
        }
    }

    /** Project index: what this project is, where work stopped, and every session newest first. */
    private fun renderIndex(dir: Path, md: SessionMarkdown): String =
        buildString {
            appendLine("# ${md.project.name}")
            appendLine()
            appendLine(md.project.description.ifBlank { "_(no project description recorded)_" })
            appendLine()
            appendLine("## Resume here")
            appendLine()
            appendLine("- **Last session:** ${md.session.toolName}, ${md.session.startTime}")
            appendLine("- **What was done:** ${md.session.summary.ifBlank { "_(none recorded)_" }}")
            appendLine("- **Where we stopped:** ${md.session.nextStep.ifBlank { "_(none recorded)_" }}")
            appendLine("- **Full detail:** [$LATEST_FILE]($LATEST_FILE)")
            appendLine()
            appendLine("## Sessions")
            appendLine()
            sessionFilesNewestFirst(dir).forEach { appendLine("- [$it]($it)") }
            appendLine()
            appendLine("_Generated by SCP on every update_context. Edits to this file are overwritten._")
        }

    /**
     * Session files only — never LATEST.md, PROJECT.md, or a leftover temp file. The name format
     * sorts chronologically, so reversing the sorted list gives newest first without parsing dates.
     */
    private fun sessionFilesNewestFirst(dir: Path): List<String> {
        val names =
            Files.list(dir).use { stream ->
                stream
                    .map { it.fileName.toString() }
                    .filter { it.endsWith(".md") && it != LATEST_FILE && it != INDEX_FILE }
                    .sorted()
                    .toList()
            }
        return names.asReversed()
    }

    private fun render(md: SessionMarkdown): String {
        val session = md.session
        val byType = md.entries.groupBy { it.type }
        val decisionEntries = (byType[ContextType.DECISION].orEmpty()) + (byType[ContextType.ARCHITECTURE].orEmpty())
        val taskEntries = byType[ContextType.TASK].orEmpty()
        val bugEntries = byType[ContextType.BUG].orEmpty()
        val promptEntries = byType[ContextType.PROMPT].orEmpty()
        val coveredTypes = setOf(ContextType.DECISION, ContextType.ARCHITECTURE, ContextType.TASK, ContextType.BUG, ContextType.PROMPT)
        val noteEntries = md.entries.filterNot { it.type in coveredTypes }

        return buildString {
            appendLine("# Session")
            appendLine()
            appendLine("Date: ${session.startTime.toLocalDateTime(TimeZone.UTC).date}")
            appendLine("AI Tool: ${session.toolName}")
            appendLine("Session ID: ${session.id}")
            appendLine("Status: ${session.status.dbValue}")
            appendLine("Summary: ${session.summary.ifBlank { "(none)" }}")
            appendLine("Next step: ${session.nextStep.ifBlank { "(none)" }}")
            appendLine()
            section("Architecture Decisions") {
                md.decisions.forEach { appendLine("- **${it.title}** — ${it.decision}${reason(it.reason)}") }
                decisionEntries.forEach { appendEntry(it) }
            }
            section("Tasks Completed") {
                taskEntries.forEach { appendEntry(it) }
            }
            section("Open Issues") {
                md.todos.forEach { appendLine("- [ ] ${it.description}${it.owner?.let { o -> " (owner: $o)" } ?: ""}") }
                bugEntries.forEach { appendEntry(it) }
            }
            section("Files Modified") {
                md.files.forEach { appendLine("- `${it.path}`${if (it.summary.isBlank()) "" else " — ${it.summary}"}") }
            }
            section("Prompts") {
                promptEntries.forEach { appendEntry(it) }
            }
            section("Notes") {
                noteEntries.forEach { appendEntry(it) }
            }
        }
    }

    private fun StringBuilder.section(title: String, body: StringBuilder.() -> Unit) {
        appendLine("## $title")
        val lengthBefore = length
        body()
        if (length == lengthBefore) appendLine("_(none)_")
        appendLine()
    }

    private fun StringBuilder.appendEntry(entry: ContextEntry) {
        val tags = if (entry.tags.isEmpty()) "" else " [${entry.tags.joinToString(", ")}]"
        appendLine("- **${entry.title}**$tags (${entry.type.name.lowercase()}, priority ${entry.priority})")
        entry.content.lineSequence().forEach { appendLine("  $it") }
    }

    private fun reason(reason: String): String = if (reason.isBlank()) "" else " (reason: $reason)"

    private companion object {
        const val SESSION_ID_CHARS = 8
        const val LATEST_FILE = "LATEST.md"
        const val INDEX_FILE = "PROJECT.md"

        /**
         * One lock per project directory, keyed by absolute path so two FileMarkdownStore
         * instances over the same root share it — the same approach SqliteTransactionRunner
         * takes for the database. In-process only: it orders the writers inside one JVM, which
         * is where concurrent agents in a single MCP server actually collide. Each individual
         * write is still atomic (temp file + move), so a second process can at worst interleave
         * whole files, never corrupt one.
         */
        private val directoryLocks = ConcurrentHashMap<String, ReentrantLock>()

        fun lockFor(dir: Path): ReentrantLock =
            directoryLocks.computeIfAbsent(dir.toAbsolutePath().normalize().toString()) { ReentrantLock() }

        /**
         * `{YYYY-MM-DD}T{HH-mm-ss}Z-{tool}-{id8}.md` — UTC, and `:` replaced with `-` because
         * Windows forbids it in filenames. Sorts chronologically as plain text.
         */
        fun sessionFileName(startTime: Instant, toolName: String, sessionId: String): String {
            val utc = startTime.toLocalDateTime(TimeZone.UTC)
            val time = "%02d-%02d-%02d".format(utc.hour, utc.minute, utc.second)
            return "${utc.date}T${time}Z-${sanitizeForDirectory(toolName)}-${sessionId.take(SESSION_ID_CHARS)}.md"
        }

        /** Windows-safe directory name: forbidden characters replaced, trailing dots/spaces trimmed. */
        fun sanitizeForDirectory(name: String): String {
            val cleaned =
                name
                    .map { c -> if (c.isISOControl() || c in "<>:\"/\\|?*") '-' else c }
                    .joinToString("")
                    .trim()
                    .trimEnd('.', ' ')
            return cleaned.ifBlank { "unnamed-project" }
        }
    }
}
